#!/usr/bin/env ruby
# frozen_string_literal: true

STDOUT.sync = true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require 'rubaheui'
require 'mercenary'

Mercenary.program(:rubaheui) do |p|
  p.version Rubaheui::VERSION
  p.description "Rubaheui is The Aheui implementation written in Ruby."
  p.syntax "rubaheui <subcommand> [args]"

  # p.option "file", "<PATH>", "Run Aheui code from file."
  # p.option "inline", "[code]", "Run Aheui code from standard input."

  # Rubaheui::Commands.subclasses.each { |c| c.init_with_program(p) }

  p.command(:file) do |c|
    c.syntax "file <PATH>"
    c.description "Run Aheui code from file."
    c.action do |args|
      Rubaheui::Commands::File.process(args)
    end
  end

  p.command(:run) do |c|
    c.syntax "run"
    c.description "(for dev) Run specified function that declared on `lib/rubaheui/commands/run`."
    c.action do
      Rubaheui::Commands::Run.process
    end
  end
end